/******************************************
Treehouse Techdegree:
FSJS project 1 - A Random Quote Generator
******************************************/

var quotes = [
  {
    quote: "How you make your money is more important than how much you make.",
    source: "Gary Vaynerchuk",
    year: "2016",
    citation: "YouTube",
    hashtags: null
  },
  {
    quote: "If you want is, you gotta see it with a clear-eyed view.",
    source: "Meek Mill",
    year: "2012",
    citation: "Dreams and Nightmares",
    hashtags: null
  },
  {
    quote: "Focus on your strengths, not your weaknesses.",
    source: "Gary Vaynerchuk",
    year: null,
    citation: "A-Z Quotes",
    hashtags: ["#focus", "#weaknesses"]
  },
  {
    quote: "A penguin cannot become a giraffe, so just be the best penguin you can be.",
    source: "Gary Vaynerchuk",
    year: "2014",
    citation: "Twitter",
    hashtags: ["#inspirational"]
  },
  {
    quote: "Without hustle, talent will only carry you so far.",
    source: "Gary Vaynerchuk",
    year: null,
    citation: "A-Z Quotes",
    hashtags: ["#hustle", "#talent"]
  },
  {
    quote: "Anything's possible, you gotta dream like you never seen obstacles.",
    source: "J. Cole",
    year: "2010",
    citation: "The Autograph",
    hashtags: ["#dreams", "#obstacles"]
  },
  {
    quote: "Life is a movie, pick your own role, Climb your own ladder or you dig your own hole.",
    source: "J. Cole",
    year: "2011",
    citation: "How High",
    hashtags: ["#life", "#ladders"]
  }
];

var randNum;
var randQuote;
var quote;
var source;
var citation;
var year;
var hashtags;
var bgColors = ["#33d9b2", "#40407a", "#34ace0", "#ff5252", "#ff793f", "#ffb142"];
var randBgColor;

// Generates and returns a random number from 0 to the length of the array provided
function getRandomQuote(quotesArray) {
  randNum = Math.floor(Math.random() * quotesArray.length);
  return quotesArray[randNum];
}

// Sets the background color to a random color in the given array
function changeBg(bgArray) {
  randBgColor = getRandomQuote(bgArray);
  document.body.style.backgroundColor = randBgColor;
  document.getElementById("loadQuote").style.backgroundColor = randBgColor;
}

// Sets the random number generated by the `getRandomoQuote` function and equals it to variable `randQuote`
function printQuote() {
  randQuote = getRandomQuote(quotes);

  // A set of variables are assigned to a code snippet
  quote = '<p class="quote">' + randQuote.quote + '</p>';
  source = '<p class="source">' + randQuote.source;

  // Conditional statements check if the optional values are set. Values are set blank if the values are equal to null
  if(randQuote.citation === null) {
    citation = "";
  } else {
    citation = '<span class="citation">' + randQuote.citation + '</span>';
  }

  if(randQuote.year === null) {
    year = "";
  } else {
    year = '<span class="year">' + randQuote.year + '</span>';
  }

  if(randQuote.hashtags === null) {
    hashtags = "";
  } else {
    hashtags = '<span class="hashtags">' + randQuote.hashtags.join(", ") + '</span>';
  }  

  if(randQuote.year === null) {
    year = "";
  }

  // Insert the code snippets into the `quote-box` div
  document.getElementById("quote-box").innerHTML = quote + source + citation + year + hashtags + "</p>";
  
  // Changes the background color everytime the 'Show another quote' button is clicked
  changeBg(bgColors);
}

// Loads a random quote when the page is loaded
printQuote();

// Loads a new random quote every 20 seconds
setInterval(printQuote, 20000);


// Loads a random quote when the 'Show another quote' button is clicked
document.getElementById('loadQuote').addEventListener("click", printQuote, false);